global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "ml-serving"
    metrics_path: /metrics
    static_configs:
      - targets: ["inference:8000"]

  - job_name: "ml-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["exporter:9000"]