services:
  inference:
    build: .
    container_name: inference
    command: ["uvicorn", "inference:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"

  exporter:
    build: .
    container_name: exporter
    command: ["python", "prometheus_exporter.py"]
    ports:
      - "9000:9000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./2.prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - inference
      - exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
